/**
 * Single source of truth for the web action engine.
 *
 * Clip / menu / posture keys are canonical enum values only — no aliases.
 */
import { PetActionClip } from '@/enums/pet-action-clip';
import { PetActionMenuItem } from '@/enums/pet-action-menu-item';
import { PetActionPosture } from '@/enums/pet-action-posture';
import type { ActionEngineConfig } from '@/lib/action-engine/action-engine';

export type ActionPosture = `${PetActionPosture}`;
export type ActionClipKey = `${PetActionClip}`;
export type ActionMenuItemKey = `${PetActionMenuItem}`;

export const actionConfig = {
  version: 1,
  defaultClip: PetActionClip.SitIdle,
  postures: {
    [PetActionPosture.Sitting]: {
      sustainedClips: [PetActionClip.SitIdle],
    },
    [PetActionPosture.WalkingLeft]: {
      sustainedClips: [PetActionClip.WalkLeftLoop],
    },
    [PetActionPosture.WalkingRight]: {
      sustainedClips: [PetActionClip.WalkRightLoop],
    },
    [PetActionPosture.Sleeping]: {
      sustainedClips: [PetActionClip.SleepLoop],
    },
  },
  clips: {
    [PetActionClip.SitIdle]: {
      posture: PetActionPosture.Sitting,
      plannerPosture: PetActionPosture.Sitting,
      loop: true,
      logicalAction: null,
      firstFrameContract: 'front_sitting_pose',
      lastFrameContract: 'front_sitting_pose_loop',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [
        PetActionClip.SitIdle,
        PetActionClip.SitToWalkLeft,
        PetActionClip.SitToWalkRight,
        PetActionClip.Lick,
        PetActionClip.Scratch,
        PetActionClip.Tease,
        PetActionClip.LieDown,
      ],
    },
    [PetActionClip.SitToWalkLeft]: {
      posture: PetActionPosture.WalkingLeft,
      plannerPosture: PetActionPosture.Sitting,
      loop: false,
      logicalAction: PetActionMenuItem.WalkLeft,
      firstFrameContract: 'sit_idle/frame_000',
      lastFrameContract: 'walk_left_loop/entry_phase',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.WalkLeftLoop],
    },
    [PetActionClip.SitToWalkRight]: {
      posture: PetActionPosture.WalkingRight,
      plannerPosture: PetActionPosture.Sitting,
      loop: false,
      logicalAction: PetActionMenuItem.WalkRight,
      firstFrameContract: 'sit_idle/frame_000',
      lastFrameContract: 'walk_right_loop/entry_phase',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.WalkRightLoop],
    },
    [PetActionClip.WalkLeftLoop]: {
      posture: PetActionPosture.WalkingLeft,
      plannerPosture: PetActionPosture.WalkingLeft,
      loop: true,
      logicalAction: PetActionMenuItem.WalkLeft,
      firstFrameContract: 'stable_left_walk_phase',
      lastFrameContract: 'seamless_left_walk_loop',
      internalMovement: true,
      windowMovement: true,
      scaleChange: false,
      successors: [
        PetActionClip.WalkLeftLoop,
        PetActionClip.TurnLeftToRight,
        PetActionClip.WalkLeftToSit,
      ],
    },
    [PetActionClip.WalkRightLoop]: {
      posture: PetActionPosture.WalkingRight,
      plannerPosture: PetActionPosture.WalkingRight,
      loop: true,
      logicalAction: PetActionMenuItem.WalkRight,
      firstFrameContract: 'stable_right_walk_phase',
      lastFrameContract: 'seamless_right_walk_loop',
      internalMovement: true,
      windowMovement: true,
      scaleChange: false,
      successors: [
        PetActionClip.WalkRightLoop,
        PetActionClip.TurnRightToLeft,
        PetActionClip.WalkRightToSit,
        PetActionClip.BreakStretchToSit,
      ],
    },
    [PetActionClip.TurnLeftToRight]: {
      posture: PetActionPosture.WalkingRight,
      plannerPosture: PetActionPosture.WalkingLeft,
      loop: false,
      logicalAction: PetActionMenuItem.WalkRight,
      firstFrameContract: 'walk_left_loop/footfall_phase',
      lastFrameContract: 'right_walk_or_right_sit_handoff',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.WalkRightLoop, PetActionClip.WalkRightToSit],
    },
    [PetActionClip.TurnRightToLeft]: {
      posture: PetActionPosture.WalkingLeft,
      plannerPosture: PetActionPosture.WalkingRight,
      loop: false,
      logicalAction: PetActionMenuItem.WalkLeft,
      firstFrameContract: 'walk_right_loop/footfall_phase',
      lastFrameContract: 'walk_left_loop/entry_phase',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.WalkLeftLoop, PetActionClip.WalkLeftToSit],
    },
    [PetActionClip.WalkLeftToSit]: {
      posture: PetActionPosture.WalkingLeft,
      plannerPosture: PetActionPosture.WalkingLeft,
      loop: false,
      logicalAction: PetActionMenuItem.SitDown,
      firstFrameContract: 'walk_left_loop/footfall_phase',
      lastFrameContract: 'sit_idle/frame_000',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SitIdle],
    },
    [PetActionClip.WalkRightToSit]: {
      posture: PetActionPosture.WalkingRight,
      plannerPosture: PetActionPosture.WalkingRight,
      loop: false,
      logicalAction: PetActionMenuItem.SitDown,
      firstFrameContract: 'walk_right_loop/footfall_phase',
      lastFrameContract: 'sit_idle/frame_000',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SitIdle],
    },
    [PetActionClip.BreakStretchToSit]: {
      posture: PetActionPosture.WalkingRight,
      plannerPosture: PetActionPosture.WalkingRight,
      loop: false,
      logicalAction: PetActionMenuItem.Stretch,
      firstFrameContract: 'walk_right_loop/stable_phase',
      lastFrameContract: 'sit_idle/frame_000',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SitIdle],
    },
    [PetActionClip.Lick]: {
      posture: PetActionPosture.Sitting,
      plannerPosture: PetActionPosture.Sitting,
      loop: false,
      logicalAction: PetActionMenuItem.Lick,
      firstFrameContract: 'front_sitting_pose',
      lastFrameContract: 'front_sitting_pose',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SitIdle],
    },
    [PetActionClip.Scratch]: {
      posture: PetActionPosture.Sitting,
      plannerPosture: PetActionPosture.Sitting,
      loop: false,
      logicalAction: PetActionMenuItem.Scratch,
      firstFrameContract: 'front_sitting_pose',
      lastFrameContract: 'front_sitting_pose',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SitIdle],
    },
    [PetActionClip.Tease]: {
      posture: PetActionPosture.Sitting,
      plannerPosture: PetActionPosture.Sitting,
      loop: false,
      logicalAction: PetActionMenuItem.Tease,
      firstFrameContract: 'front_sitting_pose',
      lastFrameContract: 'front_sitting_pose',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SitIdle],
    },
    [PetActionClip.LieDown]: {
      posture: PetActionPosture.Sleeping,
      plannerPosture: PetActionPosture.Sitting,
      loop: false,
      logicalAction: PetActionMenuItem.Sleep,
      firstFrameContract: 'front_sitting_pose',
      lastFrameContract: 'sleeping_pose',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SleepLoop],
    },
    [PetActionClip.SleepLoop]: {
      posture: PetActionPosture.Sleeping,
      plannerPosture: PetActionPosture.Sleeping,
      loop: true,
      logicalAction: PetActionMenuItem.Sleep,
      firstFrameContract: 'sleeping_pose',
      lastFrameContract: 'seamless_sleep_loop',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [
        PetActionClip.SleepLoop,
        PetActionClip.CoverEyes,
        PetActionClip.SleepTurn,
        PetActionClip.WakeUp,
      ],
    },
    [PetActionClip.CoverEyes]: {
      posture: PetActionPosture.Sleeping,
      plannerPosture: PetActionPosture.Sleeping,
      loop: false,
      logicalAction: PetActionMenuItem.Sleep,
      firstFrameContract: 'sleeping_pose',
      lastFrameContract: 'sleeping_pose',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SleepLoop],
    },
    [PetActionClip.SleepTurn]: {
      posture: PetActionPosture.Sleeping,
      plannerPosture: PetActionPosture.Sleeping,
      loop: false,
      logicalAction: PetActionMenuItem.Sleep,
      firstFrameContract: 'sleeping_pose',
      lastFrameContract: 'sleeping_pose',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SleepLoop],
    },
    [PetActionClip.WakeUp]: {
      posture: PetActionPosture.Sitting,
      plannerPosture: PetActionPosture.Sitting,
      loop: false,
      logicalAction: PetActionMenuItem.WakeUp,
      firstFrameContract: 'sleeping_pose',
      lastFrameContract: 'front_sitting_pose',
      internalMovement: true,
      windowMovement: false,
      scaleChange: false,
      successors: [PetActionClip.SitIdle],
    },
  },
  contractChains: {
    sit_to_walk_right: [
      PetActionClip.SitIdle,
      PetActionClip.SitToWalkRight,
      PetActionClip.WalkRightLoop,
    ],
    walk_right_to_sit: [
      PetActionClip.WalkRightLoop,
      PetActionClip.WalkRightToSit,
      PetActionClip.SitIdle,
    ],
    sit_to_walk_left: [
      PetActionClip.SitIdle,
      PetActionClip.SitToWalkLeft,
      PetActionClip.WalkLeftLoop,
    ],
    walk_left_turn_to_right_sit: [
      PetActionClip.WalkLeftLoop,
      PetActionClip.TurnLeftToRight,
      PetActionClip.WalkRightToSit,
      PetActionClip.SitIdle,
    ],
    stretch_to_sit: [
      PetActionClip.WalkRightLoop,
      PetActionClip.BreakStretchToSit,
      PetActionClip.SitIdle,
    ],
    lick_to_sit: [
      PetActionClip.SitIdle,
      PetActionClip.Lick,
      PetActionClip.SitIdle,
    ],
    scratch_to_sit: [
      PetActionClip.SitIdle,
      PetActionClip.Scratch,
      PetActionClip.SitIdle,
    ],
    tease_to_sit: [
      PetActionClip.SitIdle,
      PetActionClip.Tease,
      PetActionClip.SitIdle,
    ],
    wake_to_sit: [
      PetActionClip.SleepLoop,
      PetActionClip.WakeUp,
      PetActionClip.SitIdle,
    ],
  },
  previewChains: {
    sit_to_walk_right: [
      PetActionClip.SitIdle,
      PetActionClip.SitToWalkRight,
      PetActionClip.WalkRightLoop,
    ],
    walk_right_to_sit: [
      PetActionClip.WalkRightLoop,
      PetActionClip.WalkRightToSit,
      PetActionClip.SitIdle,
    ],
    sit_to_walk_left: [
      PetActionClip.SitIdle,
      PetActionClip.SitToWalkLeft,
      PetActionClip.WalkLeftLoop,
    ],
    walk_left_turn_to_right_sit: [
      PetActionClip.WalkLeftLoop,
      PetActionClip.TurnLeftToRight,
      PetActionClip.WalkRightToSit,
      PetActionClip.SitIdle,
    ],
    stretch_to_sit: [
      PetActionClip.WalkRightLoop,
      PetActionClip.BreakStretchToSit,
      PetActionClip.SitIdle,
    ],
    lick_to_sit: [
      PetActionClip.SitIdle,
      PetActionClip.Lick,
      PetActionClip.SitIdle,
    ],
    scratch_to_sit: [
      PetActionClip.SitIdle,
      PetActionClip.Scratch,
      PetActionClip.SitIdle,
    ],
    tease_to_sit: [
      PetActionClip.SitIdle,
      PetActionClip.Tease,
      PetActionClip.SitIdle,
    ],
    wake_to_sit: [
      PetActionClip.SleepLoop,
      PetActionClip.WakeUp,
      PetActionClip.SitIdle,
    ],
  },
  menuItems: {
    [PetActionMenuItem.Sleep]: {
      labelKey: 'sleep',
      label: 'Sleep',
      group: 'status',
      transitions: [
        {
          from: PetActionPosture.Sitting,
          requires: [PetActionClip.LieDown, PetActionClip.SleepLoop],
          play: [PetActionClip.LieDown, PetActionClip.SleepLoop],
          to: PetActionPosture.Sleeping,
        },
      ],
    },
    [PetActionMenuItem.WakeUp]: {
      labelKey: 'wakeUp',
      label: 'Wake Up',
      group: 'status',
      transitions: [
        {
          from: PetActionPosture.Sleeping,
          requires: [PetActionClip.WakeUp, PetActionClip.SitIdle],
          play: [PetActionClip.WakeUp, PetActionClip.SitIdle],
          to: PetActionPosture.Sitting,
        },
      ],
    },
    [PetActionMenuItem.Lick]: {
      labelKey: 'lick',
      label: 'Lick',
      group: 'sit',
      transitions: [
        {
          from: PetActionPosture.Sitting,
          requires: [PetActionClip.Lick, PetActionClip.SitIdle],
          play: [PetActionClip.Lick, PetActionClip.SitIdle],
          to: PetActionPosture.Sitting,
        },
      ],
    },
    [PetActionMenuItem.Scratch]: {
      labelKey: 'scratch',
      label: 'Scratch',
      group: 'sit',
      transitions: [
        {
          from: PetActionPosture.Sitting,
          requires: [PetActionClip.Scratch, PetActionClip.SitIdle],
          play: [PetActionClip.Scratch, PetActionClip.SitIdle],
          to: PetActionPosture.Sitting,
        },
      ],
    },
    [PetActionMenuItem.Tease]: {
      labelKey: 'tease',
      label: 'Tease',
      group: 'sit',
      transitions: [
        {
          from: PetActionPosture.Sitting,
          requires: [PetActionClip.Tease, PetActionClip.SitIdle],
          play: [PetActionClip.Tease, PetActionClip.SitIdle],
          to: PetActionPosture.Sitting,
        },
      ],
    },
    [PetActionMenuItem.WalkRight]: {
      labelKey: 'walkRight',
      label: 'Walk Right',
      group: 'walk',
      transitions: [
        {
          from: PetActionPosture.Sitting,
          requires: [PetActionClip.SitToWalkRight, PetActionClip.WalkRightLoop],
          play: [PetActionClip.SitToWalkRight, PetActionClip.WalkRightLoop],
          to: PetActionPosture.WalkingRight,
        },
        {
          from: PetActionPosture.WalkingLeft,
          requires: [
            PetActionClip.TurnLeftToRight,
            PetActionClip.WalkRightLoop,
          ],
          play: [PetActionClip.TurnLeftToRight, PetActionClip.WalkRightLoop],
          to: PetActionPosture.WalkingRight,
        },
        {
          from: PetActionPosture.WalkingRight,
          requires: [PetActionClip.WalkRightLoop],
          play: [PetActionClip.WalkRightLoop],
          to: PetActionPosture.WalkingRight,
        },
      ],
    },
    [PetActionMenuItem.WalkLeft]: {
      labelKey: 'walkLeft',
      label: 'Walk Left',
      group: 'walk',
      transitions: [
        {
          from: PetActionPosture.Sitting,
          requires: [PetActionClip.SitToWalkLeft, PetActionClip.WalkLeftLoop],
          play: [PetActionClip.SitToWalkLeft, PetActionClip.WalkLeftLoop],
          to: PetActionPosture.WalkingLeft,
        },
        {
          from: PetActionPosture.WalkingRight,
          requires: [PetActionClip.TurnRightToLeft, PetActionClip.WalkLeftLoop],
          play: [PetActionClip.TurnRightToLeft, PetActionClip.WalkLeftLoop],
          to: PetActionPosture.WalkingLeft,
        },
        {
          from: PetActionPosture.WalkingLeft,
          requires: [PetActionClip.WalkLeftLoop],
          play: [PetActionClip.WalkLeftLoop],
          to: PetActionPosture.WalkingLeft,
        },
      ],
    },
    [PetActionMenuItem.SitDown]: {
      labelKey: 'sitDown',
      label: 'Sit Down',
      group: 'walk',
      transitions: [
        {
          from: PetActionPosture.WalkingLeft,
          requires: [PetActionClip.WalkLeftToSit, PetActionClip.SitIdle],
          play: [PetActionClip.WalkLeftToSit, PetActionClip.SitIdle],
          to: PetActionPosture.Sitting,
        },
        {
          from: PetActionPosture.WalkingRight,
          requires: [PetActionClip.WalkRightToSit, PetActionClip.SitIdle],
          play: [PetActionClip.WalkRightToSit, PetActionClip.SitIdle],
          to: PetActionPosture.Sitting,
        },
      ],
    },
    [PetActionMenuItem.Stretch]: {
      labelKey: 'stretch',
      label: 'Stretch',
      group: 'walk',
      transitions: [
        {
          from: PetActionPosture.WalkingRight,
          requires: [PetActionClip.BreakStretchToSit, PetActionClip.SitIdle],
          play: [PetActionClip.BreakStretchToSit, PetActionClip.SitIdle],
          to: PetActionPosture.Sitting,
        },
      ],
    },
  },
  menuOrder: [
    PetActionMenuItem.Sleep,
    PetActionMenuItem.WakeUp,
    PetActionMenuItem.Lick,
    PetActionMenuItem.Scratch,
    PetActionMenuItem.Tease,
    PetActionMenuItem.WalkRight,
    PetActionMenuItem.WalkLeft,
    PetActionMenuItem.SitDown,
    PetActionMenuItem.Stretch,
  ],
  manualHoldActions: [
    PetActionMenuItem.Sleep,
    PetActionMenuItem.WakeUp,
    PetActionMenuItem.SitDown,
    PetActionMenuItem.WalkLeft,
    PetActionMenuItem.WalkRight,
  ],
  autoplay: {
    preferences: {
      [PetActionPosture.Sitting]: [
        PetActionMenuItem.Lick,
        PetActionMenuItem.Scratch,
        PetActionMenuItem.Tease,
        PetActionMenuItem.WalkLeft,
        PetActionMenuItem.WalkRight,
        PetActionMenuItem.Sleep,
      ],
      [PetActionPosture.WalkingLeft]: [
        PetActionMenuItem.WalkLeft,
        PetActionMenuItem.WalkRight,
        PetActionMenuItem.SitDown,
      ],
      [PetActionPosture.WalkingRight]: [
        PetActionMenuItem.WalkRight,
        PetActionMenuItem.WalkLeft,
        PetActionMenuItem.SitDown,
        PetActionMenuItem.Stretch,
      ],
      [PetActionPosture.Sleeping]: [PetActionMenuItem.WakeUp],
    },
    avoidImmediateRepeat: true,
    allowRepeat: {},
    avoidAfter: {
      [PetActionMenuItem.WakeUp]: [PetActionMenuItem.Sleep],
    },
    dwellLoops: {
      [PetActionPosture.Sitting]: { min: 2, max: 3 },
      [PetActionPosture.WalkingLeft]: { min: 2, max: 4 },
      [PetActionPosture.WalkingRight]: { min: 2, max: 4 },
      [PetActionPosture.Sleeping]: { min: 3, max: 5 },
    },
  },
} as const satisfies ActionEngineConfig<
  ActionClipKey,
  ActionMenuItemKey,
  ActionPosture
>;

export type ActionConfig = typeof actionConfig;
export type ActionTransitionRule =
  ActionConfig['menuItems'][ActionMenuItemKey]['transitions'][number];
