/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ExpenseRouteImport } from './routes/expense'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as legalsCookieRouteImport } from './routes/(legals)/cookie'
import { Route as legalsPrivacyRouteImport } from './routes/(legals)/privacy'
import { Route as legalsTermsRouteImport } from './routes/(legals)/terms'
import { Route as pagesAboutRouteImport } from './routes/(pages)/about'
import { Route as pagesContactRouteImport } from './routes/(pages)/contact'
import { Route as pagesPricingRouteImport } from './routes/(pages)/pricing'
import { Route as testsTest404RouteImport } from './routes/(tests)/test-404'
import { Route as testsTestErrorRouteImport } from './routes/(tests)/test-error'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardActionsRouteImport } from './routes/dashboard/actions'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as PIndexRouteImport } from './routes/p/index'
import { Route as PSlugRouteImport } from './routes/p/$slug'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsFilesRouteImport } from './routes/settings/files'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsPaymentRouteImport } from './routes/settings/payment'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as ToolsDesktopPetMakerRouteImport } from './routes/tools/desktop-pet-maker'
import { Route as ToolsPetVideoMakerRouteImport } from './routes/tools/pet-video-maker'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as ApiWebhooksCreemRouteImport } from './routes/api/webhooks/creem'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiWebhooksWaffoRouteImport } from './routes/api/webhooks/waffo'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/category.$slug'
import { Route as BlogPagePageRouteImport } from './routes/blog/page.$page'
import { Route as ApiAuthExtensionGoogleRouteImport } from './routes/api/auth/extension/google'
import { Route as BlogCategorySlugPagePageRouteImport } from './routes/blog/category.$slug.page.$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRoute = ExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsCookieRoute = legalsCookieRouteImport.update({
  id: '/(legals)/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsPrivacyRoute = legalsPrivacyRouteImport.update({
  id: '/(legals)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const legalsTermsRoute = legalsTermsRouteImport.update({
  id: '/(legals)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesAboutRoute = pagesAboutRouteImport.update({
  id: '/(pages)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesContactRoute = pagesContactRouteImport.update({
  id: '/(pages)/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesPricingRoute = pagesPricingRouteImport.update({
  id: '/(pages)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const testsTest404Route = testsTest404RouteImport.update({
  id: '/(tests)/test-404',
  path: '/test-404',
  getParentRoute: () => rootRouteImport,
} as any)
const testsTestErrorRoute = testsTestErrorRouteImport.update({
  id: '/(tests)/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActionsRoute = DashboardActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const PIndexRoute = PIndexRouteImport.update({
  id: '/p/',
  path: '/p/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentRoute = SettingsPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const ToolsDesktopPetMakerRoute = ToolsDesktopPetMakerRouteImport.update({
  id: '/tools/desktop-pet-maker',
  path: '/tools/desktop-pet-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPetVideoMakerRoute = ToolsPetVideoMakerRouteImport.update({
  id: '/tools/pet-video-maker',
  path: '/tools/pet-video-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksCreemRoute = ApiWebhooksCreemRouteImport.update({
  id: '/api/webhooks/creem',
  path: '/api/webhooks/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWaffoRoute = ApiWebhooksWaffoRouteImport.update({
  id: '/api/webhooks/waffo',
  path: '/api/webhooks/waffo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPagePageRoute = BlogPagePageRouteImport.update({
  id: '/blog/page/$page',
  path: '/blog/page/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthExtensionGoogleRoute = ApiAuthExtensionGoogleRouteImport.update({
  id: '/api/auth/extension/google',
  path: '/api/auth/extension/google',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugPagePageRoute =
  BlogCategorySlugPagePageRouteImport.update({
    id: '/page/$page',
    path: '/page/$page',
    getParentRoute: () => BlogCategorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/expense': typeof ExpenseRoute
  '/health': typeof HealthRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/pets': typeof PetsRoute
  '/playground': typeof PlaygroundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/p/$slug': typeof PSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/desktop-pet-maker': typeof ToolsDesktopPetMakerRoute
  '/tools/pet-video-maker': typeof ToolsPetVideoMakerRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/p/': typeof PIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/waffo': typeof ApiWebhooksWaffoRoute
  '/blog/category/$slug': typeof BlogCategorySlugRouteWithChildren
  '/blog/page/$page': typeof BlogPagePageRoute
  '/api/auth/extension/google': typeof ApiAuthExtensionGoogleRoute
  '/blog/category/$slug/page/$page': typeof BlogCategorySlugPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/download': typeof DownloadRoute
  '/expense': typeof ExpenseRoute
  '/health': typeof HealthRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/pets': typeof PetsRoute
  '/playground': typeof PlaygroundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cookie': typeof legalsCookieRoute
  '/privacy': typeof legalsPrivacyRoute
  '/terms': typeof legalsTermsRoute
  '/about': typeof pagesAboutRoute
  '/contact': typeof pagesContactRoute
  '/pricing': typeof pagesPricingRoute
  '/test-404': typeof testsTest404Route
  '/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/p/$slug': typeof PSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/desktop-pet-maker': typeof ToolsDesktopPetMakerRoute
  '/tools/pet-video-maker': typeof ToolsPetVideoMakerRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/p': typeof PIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/waffo': typeof ApiWebhooksWaffoRoute
  '/blog/category/$slug': typeof BlogCategorySlugRouteWithChildren
  '/blog/page/$page': typeof BlogPagePageRoute
  '/api/auth/extension/google': typeof ApiAuthExtensionGoogleRoute
  '/blog/category/$slug/page/$page': typeof BlogCategorySlugPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/download': typeof DownloadRoute
  '/expense': typeof ExpenseRoute
  '/health': typeof HealthRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/pets': typeof PetsRoute
  '/playground': typeof PlaygroundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(legals)/cookie': typeof legalsCookieRoute
  '/(legals)/privacy': typeof legalsPrivacyRoute
  '/(legals)/terms': typeof legalsTermsRoute
  '/(pages)/about': typeof pagesAboutRoute
  '/(pages)/contact': typeof pagesContactRoute
  '/(pages)/pricing': typeof pagesPricingRoute
  '/(tests)/test-404': typeof testsTest404Route
  '/(tests)/test-error': typeof testsTestErrorRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/ping': typeof ApiPingRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/p/$slug': typeof PSlugRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/payment': typeof SettingsPaymentRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tools/desktop-pet-maker': typeof ToolsDesktopPetMakerRoute
  '/tools/pet-video-maker': typeof ToolsPetVideoMakerRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/p/': typeof PIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/webhooks/creem': typeof ApiWebhooksCreemRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/api/webhooks/waffo': typeof ApiWebhooksWaffoRoute
  '/blog/category/$slug': typeof BlogCategorySlugRouteWithChildren
  '/blog/page/$page': typeof BlogPagePageRoute
  '/api/auth/extension/google': typeof ApiAuthExtensionGoogleRoute
  '/blog/category/$slug/page/$page': typeof BlogCategorySlugPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/download'
    | '/expense'
    | '/health'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/pets'
    | '/playground'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/test-404'
    | '/test-error'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/dashboard/actions'
    | '/dashboard/overview'
    | '/p/$slug'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/desktop-pet-maker'
    | '/tools/pet-video-maker'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/p/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/api/webhooks/waffo'
    | '/blog/category/$slug'
    | '/blog/page/$page'
    | '/api/auth/extension/google'
    | '/blog/category/$slug/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/download'
    | '/expense'
    | '/health'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/pets'
    | '/playground'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/cookie'
    | '/privacy'
    | '/terms'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/test-404'
    | '/test-error'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/dashboard/actions'
    | '/dashboard/overview'
    | '/p/$slug'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/desktop-pet-maker'
    | '/tools/pet-video-maker'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/p'
    | '/settings'
    | '/api/auth/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/api/webhooks/waffo'
    | '/blog/category/$slug'
    | '/blog/page/$page'
    | '/api/auth/extension/google'
    | '/blog/category/$slug/page/$page'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/download'
    | '/expense'
    | '/health'
    | '/manifest.json'
    | '/manifest.webmanifest'
    | '/pets'
    | '/playground'
    | '/robots.txt'
    | '/settings'
    | '/sitemap.xml'
    | '/(legals)/cookie'
    | '/(legals)/privacy'
    | '/(legals)/terms'
    | '/(pages)/about'
    | '/(pages)/contact'
    | '/(pages)/pricing'
    | '/(tests)/test-404'
    | '/(tests)/test-error'
    | '/admin/users'
    | '/api/ping'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/dashboard/actions'
    | '/dashboard/overview'
    | '/p/$slug'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/files'
    | '/settings/notifications'
    | '/settings/payment'
    | '/settings/profile'
    | '/settings/security'
    | '/tools/desktop-pet-maker'
    | '/tools/pet-video-maker'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/p/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/storage/file'
    | '/api/webhooks/creem'
    | '/api/webhooks/stripe'
    | '/api/webhooks/waffo'
    | '/blog/category/$slug'
    | '/blog/page/$page'
    | '/api/auth/extension/google'
    | '/blog/category/$slug/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  ExpenseRoute: typeof ExpenseRoute
  HealthRoute: typeof HealthRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PetsRoute: typeof PetsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  legalsCookieRoute: typeof legalsCookieRoute
  legalsPrivacyRoute: typeof legalsPrivacyRoute
  legalsTermsRoute: typeof legalsTermsRoute
  pagesAboutRoute: typeof pagesAboutRoute
  pagesContactRoute: typeof pagesContactRoute
  pagesPricingRoute: typeof pagesPricingRoute
  testsTest404Route: typeof testsTest404Route
  testsTestErrorRoute: typeof testsTestErrorRoute
  ApiPingRoute: typeof ApiPingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PSlugRoute: typeof PSlugRoute
  ToolsDesktopPetMakerRoute: typeof ToolsDesktopPetMakerRoute
  ToolsPetVideoMakerRoute: typeof ToolsPetVideoMakerRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PIndexRoute: typeof PIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiWebhooksCreemRoute: typeof ApiWebhooksCreemRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiWebhooksWaffoRoute: typeof ApiWebhooksWaffoRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRouteWithChildren
  BlogPagePageRoute: typeof BlogPagePageRoute
  ApiAuthExtensionGoogleRoute: typeof ApiAuthExtensionGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/cookie': {
      id: '/(legals)/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof legalsCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/privacy': {
      id: '/(legals)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof legalsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legals)/terms': {
      id: '/(legals)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof legalsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/about': {
      id: '/(pages)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof pagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/contact': {
      id: '/(pages)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof pagesContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/pricing': {
      id: '/(pages)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof pagesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/test-404': {
      id: '/(tests)/test-404'
      path: '/test-404'
      fullPath: '/test-404'
      preLoaderRoute: typeof testsTest404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tests)/test-error': {
      id: '/(tests)/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof testsTestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/actions': {
      id: '/dashboard/actions'
      path: '/actions'
      fullPath: '/dashboard/actions'
      preLoaderRoute: typeof DashboardActionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/p/': {
      id: '/p/'
      path: '/p'
      fullPath: '/p/'
      preLoaderRoute: typeof PIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment': {
      id: '/settings/payment'
      path: '/payment'
      fullPath: '/settings/payment'
      preLoaderRoute: typeof SettingsPaymentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/tools/desktop-pet-maker': {
      id: '/tools/desktop-pet-maker'
      path: '/tools/desktop-pet-maker'
      fullPath: '/tools/desktop-pet-maker'
      preLoaderRoute: typeof ToolsDesktopPetMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pet-video-maker': {
      id: '/tools/pet-video-maker'
      path: '/tools/pet-video-maker'
      fullPath: '/tools/pet-video-maker'
      preLoaderRoute: typeof ToolsPetVideoMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/creem': {
      id: '/api/webhooks/creem'
      path: '/api/webhooks/creem'
      fullPath: '/api/webhooks/creem'
      preLoaderRoute: typeof ApiWebhooksCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/waffo': {
      id: '/api/webhooks/waffo'
      path: '/api/webhooks/waffo'
      fullPath: '/api/webhooks/waffo'
      preLoaderRoute: typeof ApiWebhooksWaffoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/page/$page': {
      id: '/blog/page/$page'
      path: '/blog/page/$page'
      fullPath: '/blog/page/$page'
      preLoaderRoute: typeof BlogPagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/extension/google': {
      id: '/api/auth/extension/google'
      path: '/api/auth/extension/google'
      fullPath: '/api/auth/extension/google'
      preLoaderRoute: typeof ApiAuthExtensionGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug/page/$page': {
      id: '/blog/category/$slug/page/$page'
      path: '/page/$page'
      fullPath: '/blog/category/$slug/page/$page'
      preLoaderRoute: typeof BlogCategorySlugPagePageRouteImport
      parentRoute: typeof BlogCategorySlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardActionsRoute: typeof DashboardActionsRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActionsRoute: DashboardActionsRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPaymentRoute: typeof SettingsPaymentRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPaymentRoute: SettingsPaymentRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface BlogCategorySlugRouteChildren {
  BlogCategorySlugPagePageRoute: typeof BlogCategorySlugPagePageRoute
}

const BlogCategorySlugRouteChildren: BlogCategorySlugRouteChildren = {
  BlogCategorySlugPagePageRoute: BlogCategorySlugPagePageRoute,
}

const BlogCategorySlugRouteWithChildren =
  BlogCategorySlugRoute._addFileChildren(BlogCategorySlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DownloadRoute: DownloadRoute,
  ExpenseRoute: ExpenseRoute,
  HealthRoute: HealthRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PetsRoute: PetsRoute,
  PlaygroundRoute: PlaygroundRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  legalsCookieRoute: legalsCookieRoute,
  legalsPrivacyRoute: legalsPrivacyRoute,
  legalsTermsRoute: legalsTermsRoute,
  pagesAboutRoute: pagesAboutRoute,
  pagesContactRoute: pagesContactRoute,
  pagesPricingRoute: pagesPricingRoute,
  testsTest404Route: testsTest404Route,
  testsTestErrorRoute: testsTestErrorRoute,
  ApiPingRoute: ApiPingRoute,
  BlogSlugRoute: BlogSlugRoute,
  PSlugRoute: PSlugRoute,
  ToolsDesktopPetMakerRoute: ToolsDesktopPetMakerRoute,
  ToolsPetVideoMakerRoute: ToolsPetVideoMakerRoute,
  BlogIndexRoute: BlogIndexRoute,
  PIndexRoute: PIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiWebhooksCreemRoute: ApiWebhooksCreemRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiWebhooksWaffoRoute: ApiWebhooksWaffoRoute,
  BlogCategorySlugRoute: BlogCategorySlugRouteWithChildren,
  BlogPagePageRoute: BlogPagePageRoute,
  ApiAuthExtensionGoogleRoute: ApiAuthExtensionGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
